package jetbrains.mps.lang.migration.methods;

/*Generated by MPS */

import jetbrains.mps.lang.migration.runtime.base.MigrationScriptReference;

public class HasMigrationScriptReference {
  public final MigrationScriptReference getReference() {
    throw new UnsupportedOperationException();
  }
}
