package jetbrains.mps.lang.smodelTests.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_TestEnum_FirstMemberDefaultValue extends EnumerationDescriptorBase {

  public EnumerationDescriptor_TestEnum_FirstMemberDefaultValue() {
    super(0xb02ae39f4c164545L, 0x8dfa88df16804e7eL, 0x54dc3a78e18a047L, "TestEnum_FirstMemberDefaultValue", "r:43b4d418-d4ca-4d97-ab07-31e4f3ddb3e5(jetbrains.mps.lang.smodelTests.structure)/382176667807293511");
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_a_0 = new EnumerationDescriptor.MemberDescriptor("a", "Default_A", "r:43b4d418-d4ca-4d97-ab07-31e4f3ddb3e5(jetbrains.mps.lang.smodelTests.structure)/382176667807293512");
  private final EnumerationDescriptor.MemberDescriptor VALUE_b_0 = new EnumerationDescriptor.MemberDescriptor("b", "NotDefault_B", "r:43b4d418-d4ca-4d97-ab07-31e4f3ddb3e5(jetbrains.mps.lang.smodelTests.structure)/382176667807293513");
  private final EnumerationDescriptor.MemberDescriptor VALUE_c_0 = new EnumerationDescriptor.MemberDescriptor("c", "NotDefault_C", "r:43b4d418-d4ca-4d97-ab07-31e4f3ddb3e5(jetbrains.mps.lang.smodelTests.structure)/382176667807293516");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_a_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_a_0, VALUE_b_0, VALUE_c_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "a":
        return VALUE_a_0;
      case "b":
        return VALUE_b_0;
      case "c":
        return VALUE_c_0;
    }
    return null;
  }
}
