package jetbrains.mps.lang.smodelTests.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_TestEnum_DeriveFromPresentation extends EnumerationDescriptorBase {

  public EnumerationDescriptor_TestEnum_DeriveFromPresentation() {
    super(0xb02ae39f4c164545L, 0x8dfa88df16804e7eL, 0x125bc18df9d40ef1L, "TestEnum_DeriveFromPresentation", "r:43b4d418-d4ca-4d97-ab07-31e4f3ddb3e5(jetbrains.mps.lang.smodelTests.structure)/1322863731089346289");
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_value_1_0 = new EnumerationDescriptor.MemberDescriptor("value_1", "presentation_1", "r:43b4d418-d4ca-4d97-ab07-31e4f3ddb3e5(jetbrains.mps.lang.smodelTests.structure)/1322863731089346290");
  private final EnumerationDescriptor.MemberDescriptor VALUE_value_2_0 = new EnumerationDescriptor.MemberDescriptor("value_2", "presentation_2", "r:43b4d418-d4ca-4d97-ab07-31e4f3ddb3e5(jetbrains.mps.lang.smodelTests.structure)/1322863731089346291");


  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_value_1_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_value_1_0, VALUE_value_2_0);
  }


  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "value_1":
        return VALUE_value_1_0;
      case "value_2":
        return VALUE_value_2_0;
    }
    return null;
  }
}
