package jetbrains.mps.lang.smodelTests.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.PropertySupport;
import java.util.Iterator;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class TestEnum_CustomDefaultValue_PropertySupport extends PropertySupport {
  public boolean canSetValue(String value) {
    if (value == null) {
      return true;
    }
    Iterator<TestEnum_CustomDefaultValue> constants = ListSequence.fromList(TestEnum_CustomDefaultValue.getConstants()).iterator();
    while (constants.hasNext()) {
      TestEnum_CustomDefaultValue constant = constants.next();
      if (value.equals(constant.getName())) {
        return true;
      }
    }
    return false;
  }
  public String toInternalValue(String value) {
    if (value == null) {
      return null;
    }
    Iterator<TestEnum_CustomDefaultValue> constants = ListSequence.fromList(TestEnum_CustomDefaultValue.getConstants()).iterator();
    while (constants.hasNext()) {
      TestEnum_CustomDefaultValue constant = constants.next();
      if (value.equals(constant.getName())) {
        return constant.getValueAsString();
      }
    }
    return null;
  }
  public String fromInternalValue(String value) {
    TestEnum_CustomDefaultValue constant = TestEnum_CustomDefaultValue.parseValue(value);
    if (constant != null) {
      return constant.getName();
    }
    return "";
  }
}
