package jetbrains.mps.lang.smodelTests.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.PropertySupport;
import java.util.Iterator;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class TestEnum_CustomIdentifier_PropertySupport extends PropertySupport {
  public boolean canSetValue(String value) {
    if (value == null) {
      return true;
    }
    Iterator<TestEnum_CustomIdentifier> constants = ListSequence.fromList(TestEnum_CustomIdentifier.getConstants()).iterator();
    while (constants.hasNext()) {
      TestEnum_CustomIdentifier constant = constants.next();
      if (value.equals(constant.getName())) {
        return true;
      }
    }
    return false;
  }
  public String toInternalValue(String value) {
    if (value == null) {
      return null;
    }
    Iterator<TestEnum_CustomIdentifier> constants = ListSequence.fromList(TestEnum_CustomIdentifier.getConstants()).iterator();
    while (constants.hasNext()) {
      TestEnum_CustomIdentifier constant = constants.next();
      if (value.equals(constant.getName())) {
        return constant.getValueAsString();
      }
    }
    return null;
  }
  public String fromInternalValue(String value) {
    TestEnum_CustomIdentifier constant = TestEnum_CustomIdentifier.parseValue(value);
    if (constant != null) {
      return constant.getName();
    }
    return "";
  }
}
