package jetbrains.mps.lang.smodelTests.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum TestEnum_DeriveFromPresentation {
  presentation_1("presentation_1", "value_1"),
  presentation_2("presentation_2", "value_2");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private TestEnum_DeriveFromPresentation(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<TestEnum_DeriveFromPresentation> getConstants() {
    List<TestEnum_DeriveFromPresentation> list = ListSequence.fromList(new LinkedList<TestEnum_DeriveFromPresentation>());
    ListSequence.fromList(list).addElement(TestEnum_DeriveFromPresentation.presentation_1);
    ListSequence.fromList(list).addElement(TestEnum_DeriveFromPresentation.presentation_2);
    return list;
  }
  public static TestEnum_DeriveFromPresentation getDefault() {
    return TestEnum_DeriveFromPresentation.presentation_1;
  }
  public static TestEnum_DeriveFromPresentation parseValue(String value) {
    if (value == null) {
      return TestEnum_DeriveFromPresentation.getDefault();
    }
    if (value.equals(TestEnum_DeriveFromPresentation.presentation_1.getValueAsString())) {
      return TestEnum_DeriveFromPresentation.presentation_1;
    }
    if (value.equals(TestEnum_DeriveFromPresentation.presentation_2.getValueAsString())) {
      return TestEnum_DeriveFromPresentation.presentation_2;
    }
    return TestEnum_DeriveFromPresentation.getDefault();
  }
}
