package jetbrains.mps.refactoring.runtime;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ILanguageAspect;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.refactoring.framework.IRefactoring;

/**
 * 
 * @author Artem Tikhomirov
 * @since 2018.2
 */
public interface RefactoringAspect extends ILanguageAspect {

  /**
   * 
   * @return refactorings declared in this language. May return empty collection.
   */
  @NotNull
  Collection<IRefactoring> getRefactorings();
}
