package jetbrains.mps.refactoring.runtime;

/*Generated by MPS */


/**
 * Base implementation of {@link jetbrains.mps.refactoring.runtime.RefactoringAspect } to subclass from generated code
 * 
 * @author Artem Tikhomirov
 * @since 2018.2
 */
public abstract class RefactoringAspectBase implements RefactoringAspect {
}
