package jetbrains.mps.baseLanguage.jdk8.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class RemoveDefaultModifier_QuickFix extends QuickFix_Runtime {
  public RemoveDefaultModifier_QuickFix() {
    super(new SNodePointer("r:0396c9ff-0a4d-4e54-9678-835fc58468cd(jetbrains.mps.baseLanguage.jdk8.typesystem)", "1557757632988467212"));
  }
  public String getDescription(SNode node) {
    return "Remove the 'default' modifier";
  }
  public void execute(SNode node) {
    assert SNodeOperations.isInstanceOf(node, MetaAdapterFactory.getConcept(0xfdcdc48fbfd84831L, 0xaa765abac2ffa010L, 0x40ed0df0ef40a332L, "jetbrains.mps.baseLanguage.jdk8.structure.DefaultModifier"));
    SNodeOperations.deleteNode(node);
  }
}
