package jetbrains.mps.tool.builder.converter;

/*Generated by MPS */

import java.util.Map;
import jetbrains.mps.core.platform.Platform;
import jetbrains.mps.core.platform.PlatformFactory;
import jetbrains.mps.core.platform.PlatformOptionsBuilder;
import jetbrains.mps.RuntimeFlags;
import jetbrains.mps.vfs.IFile;
import jetbrains.mps.vfs.FileSystem;
import org.jetbrains.mps.openapi.persistence.ModelFactory;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.util.FileUtil;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.extapi.persistence.FileDataSource;
import jetbrains.mps.persistence.DefaultModelPersistence;
import jetbrains.mps.persistence.MetaModelInfoProvider;
import jetbrains.mps.project.MPSExtentions;
import java.io.IOException;
import org.jetbrains.mps.openapi.persistence.ModelSaveException;
import org.jetbrains.mps.openapi.persistence.ModelLoadException;

public class ConvertToBinaryWorker {
  public ConvertToBinaryWorker() {
  }

  public void convert(final Map<String, String> map, final Boolean stripImplementation) {
    final Platform platform = PlatformFactory.initPlatform(PlatformOptionsBuilder.PERSISTENCE);
    RuntimeFlags.setMergeDriverMode(true);
    try {
      for (Map.Entry<String, String> entry : map.entrySet()) {
        convertModelToBinary(entry.getKey(), entry.getValue(), stripImplementation);
      }
    } finally {
      platform.dispose();
    }
  }

  private void convertModelToBinary(String sourceFile, String destFile, boolean stripImplementation) {
    IFile source = FileSystem.getInstance().getFile(sourceFile);
    ModelFactory modelFactory = PersistenceFacade.getInstance().getModelFactory(FileUtil.getExtension(source.getName()));
    if (modelFactory == null) {
      // assuming user knows what he's doing and supplied us with a model file, try default factory. 
      modelFactory = PersistenceFacade.getInstance().getDefaultModelFactory();
    }
    try {
      SModel model = modelFactory.load(new FileDataSource(source), DefaultModelPersistence.ContentLoadingExtentOptions.STRIP_IMPLEMENTATION, MetaModelInfoProvider.MetaInfoLoadingOption.KEEP_READ);
      PersistenceFacade.getInstance().getModelFactory(MPSExtentions.MODEL_BINARY).save(model, new FileDataSource(FileSystem.getInstance().getFileByPath(destFile)));
    } catch (RuntimeException ex) {
      System.out.printf("Conversion of %s\n", sourceFile);
      ex.printStackTrace();
      throw ex;
    } catch (IOException ex) {
      throw new RuntimeException(String.format("Failed to read model from file %s", sourceFile), ex);
    } catch (ModelSaveException e) {
      throw new RuntimeException(String.format("Failed to write model in binary format to the file %s", destFile), e);
    } catch (ModelLoadException e) {
      throw new RuntimeException(String.format("Failed to load model in binary format from the file %s", destFile), e);
    }
  }
}
