package jetbrains.mps.samples.heating.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_DayDataType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_DayDataType() {
    super(0xa7d67633e8d9473bL, 0x98ce995a7aa66941L, 0x4644aa4ce0948664L, "DayDataType", "r:3b810168-3010-426e-9275-12b4e509a27b(jetbrains.mps.samples.heating.structure)/5063359128233346660");
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_monday_0 = new EnumerationDescriptor.MemberDescriptor("monday", "Monday", "r:3b810168-3010-426e-9275-12b4e509a27b(jetbrains.mps.samples.heating.structure)/5063359128233346661");
  private final EnumerationDescriptor.MemberDescriptor VALUE_tuesday_0 = new EnumerationDescriptor.MemberDescriptor("tuesday", "Tuesday", "r:3b810168-3010-426e-9275-12b4e509a27b(jetbrains.mps.samples.heating.structure)/5063359128233346662");
  private final EnumerationDescriptor.MemberDescriptor VALUE_wednesday_0 = new EnumerationDescriptor.MemberDescriptor("wednesday", "Wednesday", "r:3b810168-3010-426e-9275-12b4e509a27b(jetbrains.mps.samples.heating.structure)/5063359128233346665");
  private final EnumerationDescriptor.MemberDescriptor VALUE_thursday_0 = new EnumerationDescriptor.MemberDescriptor("thursday", "Thursday", "r:3b810168-3010-426e-9275-12b4e509a27b(jetbrains.mps.samples.heating.structure)/5063359128233346669");
  private final EnumerationDescriptor.MemberDescriptor VALUE_friday_0 = new EnumerationDescriptor.MemberDescriptor("friday", "Friday", "r:3b810168-3010-426e-9275-12b4e509a27b(jetbrains.mps.samples.heating.structure)/5063359128233346674");
  private final EnumerationDescriptor.MemberDescriptor VALUE_saturday_0 = new EnumerationDescriptor.MemberDescriptor("saturday", "Saturday", "r:3b810168-3010-426e-9275-12b4e509a27b(jetbrains.mps.samples.heating.structure)/5063359128233346680");
  private final EnumerationDescriptor.MemberDescriptor VALUE_sunday_0 = new EnumerationDescriptor.MemberDescriptor("sunday", "Sunday", "r:3b810168-3010-426e-9275-12b4e509a27b(jetbrains.mps.samples.heating.structure)/5063359128233346687");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_monday_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_monday_0, VALUE_tuesday_0, VALUE_wednesday_0, VALUE_thursday_0, VALUE_friday_0, VALUE_saturday_0, VALUE_sunday_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "monday":
        return VALUE_monday_0;
      case "tuesday":
        return VALUE_tuesday_0;
      case "wednesday":
        return VALUE_wednesday_0;
      case "thursday":
        return VALUE_thursday_0;
      case "friday":
        return VALUE_friday_0;
      case "saturday":
        return VALUE_saturday_0;
      case "sunday":
        return VALUE_sunday_0;
    }
    return null;
  }
}
