package jetbrains.mps.baseLanguage.logging.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_Severity extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Severity() {
    super(0x760a0a8ceabb4521L, 0x8bfd65db761a9ba3L, 0x10fc53ae113L, "Severity", "r:00000000-0000-4000-0000-011c8959057f(jetbrains.mps.baseLanguage.logging.structure)/1167245107475");
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_fatal_0 = new EnumerationDescriptor.MemberDescriptor("fatal", "fatal", "r:00000000-0000-4000-0000-011c8959057f(jetbrains.mps.baseLanguage.logging.structure)/1167245107476");
  private final EnumerationDescriptor.MemberDescriptor VALUE_error_0 = new EnumerationDescriptor.MemberDescriptor("error", "error", "r:00000000-0000-4000-0000-011c8959057f(jetbrains.mps.baseLanguage.logging.structure)/1167245252932");
  private final EnumerationDescriptor.MemberDescriptor VALUE_warn_0 = new EnumerationDescriptor.MemberDescriptor("warn", "warn", "r:00000000-0000-4000-0000-011c8959057f(jetbrains.mps.baseLanguage.logging.structure)/1167245264682");
  private final EnumerationDescriptor.MemberDescriptor VALUE_debug_0 = new EnumerationDescriptor.MemberDescriptor("debug", "debug", "r:00000000-0000-4000-0000-011c8959057f(jetbrains.mps.baseLanguage.logging.structure)/1167245288119");
  private final EnumerationDescriptor.MemberDescriptor VALUE_info_0 = new EnumerationDescriptor.MemberDescriptor("info", "info", "r:00000000-0000-4000-0000-011c8959057f(jetbrains.mps.baseLanguage.logging.structure)/1169477928086");
  private final EnumerationDescriptor.MemberDescriptor VALUE_trace_0 = new EnumerationDescriptor.MemberDescriptor("trace", "trace", "r:00000000-0000-4000-0000-011c8959057f(jetbrains.mps.baseLanguage.logging.structure)/1167245293010");


  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_debug_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_fatal_0, VALUE_error_0, VALUE_warn_0, VALUE_debug_0, VALUE_info_0, VALUE_trace_0);
  }


  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "fatal":
        return VALUE_fatal_0;
      case "error":
        return VALUE_error_0;
      case "warn":
        return VALUE_warn_0;
      case "debug":
        return VALUE_debug_0;
      case "info":
        return VALUE_info_0;
      case "trace":
        return VALUE_trace_0;
    }
    return null;
  }
}
