package jetbrains.mps.samples.requirementTracking.RequirementDefinition.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int RequirementDocument = 0;
  public static final int RequirementEntry = 1;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x6144ad334164d7eL, 0xbbaf076e158e80cfL);
    builder.put(0x39ed36a1ccc9c4e7L, RequirementDocument);
    builder.put(0x39ed36a1ccc9c4ebL, RequirementEntry);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
