package jetbrains.mps.baseLanguage.unitTest.execution.tool;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.unitTest.execution.TestNodeKey;

public class TotalRow extends TestContainerRow {
  public TotalRow() {
    super("Total:", null);
  }

  @Override
  public boolean matches(TestNodeKey key) {
    return true;
  }
}
