package jetbrains.mps.baseLanguage.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import javax.swing.SwingUtilities;
import jetbrains.mps.smodel.ModelAccess;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class MethodCallsFixer_Quickfix_QuickFix extends QuickFix_Runtime {
  public MethodCallsFixer_Quickfix_QuickFix() {
    super(new SNodePointer("r:00000000-0000-4000-0000-011c895902c5(jetbrains.mps.baseLanguage.typesystem)", "7927910736746150956"));
  }
  public String getDescription(SNode node) {
    return "Resolve method call";
  }
  public void execute(SNode node) {
    // todo: this is a dirty hack to avoid selection from running away 
    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        ModelAccess.instance().executeCommand(new Runnable() {
          public void run() {
            SLinkOperations.setTarget(((SNode) MethodCallsFixer_Quickfix_QuickFix.this.getField("methodCall")[0]), MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), ((SNode) MethodCallsFixer_Quickfix_QuickFix.this.getField("properTarget")[0]));
          }
        });
      }
    });
  }
}
