package jetbrains.mps.lang.editor.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_PredefinedCellID extends EnumerationDescriptorBase {

  public EnumerationDescriptor_PredefinedCellID() {
    super(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x1e02662c4b880a97L, "PredefinedCellID", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/2162403111523060375", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_first_0 = new EnumerationDescriptor.MemberDescriptor("first", "FIRST", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/2162403111523060376", "FIRST");
  private final EnumerationDescriptor.MemberDescriptor VALUE_last_0 = new EnumerationDescriptor.MemberDescriptor("last", "LAST", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/2162403111523062256", "LAST");
  private final EnumerationDescriptor.MemberDescriptor VALUE_firstEditable_0 = new EnumerationDescriptor.MemberDescriptor("firstEditable", "FIRST_EDITABLE", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/2162403111523062252", "FIRST_EDITABLE");
  private final EnumerationDescriptor.MemberDescriptor VALUE_lastEditable_0 = new EnumerationDescriptor.MemberDescriptor("lastEditable", "LAST_EDITABLE", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/2162403111523062249", "LAST_EDITABLE");
  private final EnumerationDescriptor.MemberDescriptor VALUE_firstError_0 = new EnumerationDescriptor.MemberDescriptor("firstError", "FIRST_ERROR", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/2057482661602002109", "FIRST_ERROR");
  private final EnumerationDescriptor.MemberDescriptor VALUE_lastError_0 = new EnumerationDescriptor.MemberDescriptor("lastError", "LAST_ERROR", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/2057482661602002115", "LAST_ERROR");
  private final EnumerationDescriptor.MemberDescriptor VALUE_focusPolicy_0 = new EnumerationDescriptor.MemberDescriptor("focusPolicy", "FOCUS_POLICY", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/2057482661602002122", "FOCUS_POLICY");
  private final EnumerationDescriptor.MemberDescriptor VALUE_mostRelevant_0 = new EnumerationDescriptor.MemberDescriptor("mostRelevant", "MOST_RELEVANT", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/5933946333436767965", "MOST_RELEVANT");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_first_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_first_0, VALUE_last_0, VALUE_firstEditable_0, VALUE_lastEditable_0, VALUE_firstError_0, VALUE_lastError_0, VALUE_focusPolicy_0, VALUE_mostRelevant_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "first":
        return VALUE_first_0;
      case "last":
        return VALUE_last_0;
      case "firstEditable":
        return VALUE_firstEditable_0;
      case "lastEditable":
        return VALUE_lastEditable_0;
      case "firstError":
        return VALUE_firstError_0;
      case "lastError":
        return VALUE_lastError_0;
      case "focusPolicy":
        return VALUE_focusPolicy_0;
      case "mostRelevant":
        return VALUE_mostRelevant_0;
    }
    return null;
  }
}
