package jetbrains.mps.lang.editor.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor__FontStyle_Enum extends EnumerationDescriptorBase {

  public EnumerationDescriptor__FontStyle_Enum() {
    super(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x1006551b180L, "_FontStyle_Enum", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/1101211480448");
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_BOLD_0 = new EnumerationDescriptor.MemberDescriptor("BOLD", "bold", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/1101211523070");
  private final EnumerationDescriptor.MemberDescriptor VALUE_ITALIC_0 = new EnumerationDescriptor.MemberDescriptor("ITALIC", "italic", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/1101211542532");
  private final EnumerationDescriptor.MemberDescriptor VALUE_BOLD_ITALIC_0 = new EnumerationDescriptor.MemberDescriptor("BOLD_ITALIC", "boldItalic", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/1101213960346");
  private final EnumerationDescriptor.MemberDescriptor VALUE_PLAIN_0 = new EnumerationDescriptor.MemberDescriptor("PLAIN", "plain", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/1134577855137");
  private final EnumerationDescriptor.MemberDescriptor VALUE_QUERY_0 = new EnumerationDescriptor.MemberDescriptor("QUERY", "query", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/1220973684614");


  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_PLAIN_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_BOLD_0, VALUE_ITALIC_0, VALUE_BOLD_ITALIC_0, VALUE_PLAIN_0, VALUE_QUERY_0);
  }


  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "BOLD":
        return VALUE_BOLD_0;
      case "ITALIC":
        return VALUE_ITALIC_0;
      case "BOLD_ITALIC":
        return VALUE_BOLD_ITALIC_0;
      case "PLAIN":
        return VALUE_PLAIN_0;
      case "QUERY":
        return VALUE_QUERY_0;
    }
    return null;
  }
}
