package jetbrains.mps.lang.editor.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_CellActionId extends EnumerationDescriptorBase {

  public EnumerationDescriptor_CellActionId() {
    super(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x10951993667L, "CellActionId", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/1139535328871");
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_right_transform_action_id_0 = new EnumerationDescriptor.MemberDescriptor("right_transform_action_id", "RIGHT_TRANSFORM", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/1139535329028");
  private final EnumerationDescriptor.MemberDescriptor VALUE_delete_action_id_0 = new EnumerationDescriptor.MemberDescriptor("delete_action_id", "DELETE", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/1139535387060");
  private final EnumerationDescriptor.MemberDescriptor VALUE_insert_action_id_0 = new EnumerationDescriptor.MemberDescriptor("insert_action_id", "INSERT", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/1222746468862079483");
  private final EnumerationDescriptor.MemberDescriptor VALUE_insert_before_action_id_0 = new EnumerationDescriptor.MemberDescriptor("insert_before_action_id", "INSERT_BEFORE", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/1222746468862079484");
  private final EnumerationDescriptor.MemberDescriptor VALUE_backspace_action_id_0 = new EnumerationDescriptor.MemberDescriptor("backspace_action_id", "BACKSPACE", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657675082");
  private final EnumerationDescriptor.MemberDescriptor VALUE_delete_to_word_end_action_id_0 = new EnumerationDescriptor.MemberDescriptor("delete_to_word_end_action_id", "DELETE_TO_WORD_END", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707152");
  private final EnumerationDescriptor.MemberDescriptor VALUE_copy_action_id_0 = new EnumerationDescriptor.MemberDescriptor("copy_action_id", "COPY", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707153");
  private final EnumerationDescriptor.MemberDescriptor VALUE_cut_action_id_0 = new EnumerationDescriptor.MemberDescriptor("cut_action_id", "CUT", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707154");
  private final EnumerationDescriptor.MemberDescriptor VALUE_paste_action_id_0 = new EnumerationDescriptor.MemberDescriptor("paste_action_id", "PASTE", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707155");
  private final EnumerationDescriptor.MemberDescriptor VALUE_paste_before_action_id_0 = new EnumerationDescriptor.MemberDescriptor("paste_before_action_id", "PASTE_BEFORE", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707156");
  private final EnumerationDescriptor.MemberDescriptor VALUE_paste_after_action_id_0 = new EnumerationDescriptor.MemberDescriptor("paste_after_action_id", "PASTE_AFTER", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707157");
  private final EnumerationDescriptor.MemberDescriptor VALUE_left_action_id_0 = new EnumerationDescriptor.MemberDescriptor("left_action_id", "LEFT", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707158");
  private final EnumerationDescriptor.MemberDescriptor VALUE_right_action_id_0 = new EnumerationDescriptor.MemberDescriptor("right_action_id", "RIGHT", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707159");
  private final EnumerationDescriptor.MemberDescriptor VALUE_up_action_id_0 = new EnumerationDescriptor.MemberDescriptor("up_action_id", "UP", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707160");
  private final EnumerationDescriptor.MemberDescriptor VALUE_down_action_id_0 = new EnumerationDescriptor.MemberDescriptor("down_action_id", "DOWN", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707161");
  private final EnumerationDescriptor.MemberDescriptor VALUE_next_action_id_0 = new EnumerationDescriptor.MemberDescriptor("next_action_id", "NEXT", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707162");
  private final EnumerationDescriptor.MemberDescriptor VALUE_prev_action_id_0 = new EnumerationDescriptor.MemberDescriptor("prev_action_id", "PREV", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707163");
  private final EnumerationDescriptor.MemberDescriptor VALUE_home_action_id_0 = new EnumerationDescriptor.MemberDescriptor("home_action_id", "HOME", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707164");
  private final EnumerationDescriptor.MemberDescriptor VALUE_end_action_id_0 = new EnumerationDescriptor.MemberDescriptor("end_action_id", "END", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707165");
  private final EnumerationDescriptor.MemberDescriptor VALUE_page_up_action_id_0 = new EnumerationDescriptor.MemberDescriptor("page_up_action_id", "PAGE_UP", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707166");
  private final EnumerationDescriptor.MemberDescriptor VALUE_page_down_action_id_0 = new EnumerationDescriptor.MemberDescriptor("page_down_action_id", "PAGE_DOWN", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707167");
  private final EnumerationDescriptor.MemberDescriptor VALUE_root_home_action_id_0 = new EnumerationDescriptor.MemberDescriptor("root_home_action_id", "ROOT_HOME", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707168");
  private final EnumerationDescriptor.MemberDescriptor VALUE_root_end_action_id_0 = new EnumerationDescriptor.MemberDescriptor("root_end_action_id", "ROOT_END", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707169");
  private final EnumerationDescriptor.MemberDescriptor VALUE_local_home_action_id_0 = new EnumerationDescriptor.MemberDescriptor("local_home_action_id", "LOCAL_HOME", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707170");
  private final EnumerationDescriptor.MemberDescriptor VALUE_local_end_action_id_0 = new EnumerationDescriptor.MemberDescriptor("local_end_action_id", "LOCAL_END", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707171");
  private final EnumerationDescriptor.MemberDescriptor VALUE_select_all_action_id_0 = new EnumerationDescriptor.MemberDescriptor("select_all_action_id", "SELECT_ALL", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/5087404372099706598");
  private final EnumerationDescriptor.MemberDescriptor VALUE_select_left_action_id_0 = new EnumerationDescriptor.MemberDescriptor("select_left_action_id", "SELECT_LEFT", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707172");
  private final EnumerationDescriptor.MemberDescriptor VALUE_select_right_action_id_0 = new EnumerationDescriptor.MemberDescriptor("select_right_action_id", "SELECT_RIGHT", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707173");
  private final EnumerationDescriptor.MemberDescriptor VALUE_select_up_action_id_0 = new EnumerationDescriptor.MemberDescriptor("select_up_action_id", "SELECT_UP", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707174");
  private final EnumerationDescriptor.MemberDescriptor VALUE_select_down_action_id_0 = new EnumerationDescriptor.MemberDescriptor("select_down_action_id", "SELECT_DOWN", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707175");
  private final EnumerationDescriptor.MemberDescriptor VALUE_select_home_action_id_0 = new EnumerationDescriptor.MemberDescriptor("select_home_action_id", "SELECT_HOME", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707176");
  private final EnumerationDescriptor.MemberDescriptor VALUE_select_end_action_id_0 = new EnumerationDescriptor.MemberDescriptor("select_end_action_id", "SELECT_END", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707177");
  private final EnumerationDescriptor.MemberDescriptor VALUE_select_local_end_action_id_0 = new EnumerationDescriptor.MemberDescriptor("select_local_end_action_id", "SELECT_LOCAL_END", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707178");
  private final EnumerationDescriptor.MemberDescriptor VALUE_select_local_home_action_id_0 = new EnumerationDescriptor.MemberDescriptor("select_local_home_action_id", "SELECT_LOCAL_HOME", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707179");
  private final EnumerationDescriptor.MemberDescriptor VALUE_select_next_action_id_0 = new EnumerationDescriptor.MemberDescriptor("select_next_action_id", "SELECT_NEXT", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707180");
  private final EnumerationDescriptor.MemberDescriptor VALUE_select_previous_action_id_0 = new EnumerationDescriptor.MemberDescriptor("select_previous_action_id", "SELECT_PREVIOUS", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707181");
  private final EnumerationDescriptor.MemberDescriptor VALUE_left_transform_action_id_0 = new EnumerationDescriptor.MemberDescriptor("left_transform_action_id", "LEFT_TRANSFORM", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707182");
  private final EnumerationDescriptor.MemberDescriptor VALUE_complete_action_id_0 = new EnumerationDescriptor.MemberDescriptor("complete_action_id", "COMPLETE", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707183");
  private final EnumerationDescriptor.MemberDescriptor VALUE_complete_smart_action_id_0 = new EnumerationDescriptor.MemberDescriptor("complete_smart_action_id", "COMPLETE_SMART", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707184");
  private final EnumerationDescriptor.MemberDescriptor VALUE_fold_action_id_0 = new EnumerationDescriptor.MemberDescriptor("fold_action_id", "FOLD", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707185");
  private final EnumerationDescriptor.MemberDescriptor VALUE_unfold_action_id_0 = new EnumerationDescriptor.MemberDescriptor("unfold_action_id", "UNFOLD", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707186");
  private final EnumerationDescriptor.MemberDescriptor VALUE_fold_all_action_id_0 = new EnumerationDescriptor.MemberDescriptor("fold_all_action_id", "FOLD_ALL", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707187");
  private final EnumerationDescriptor.MemberDescriptor VALUE_unfold_all_action_id_0 = new EnumerationDescriptor.MemberDescriptor("unfold_all_action_id", "UNFOLD_ALL", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707188");
  private final EnumerationDescriptor.MemberDescriptor VALUE_toggle_folding_action_id_0 = new EnumerationDescriptor.MemberDescriptor("toggle_folding_action_id", "TOGGLE_FOLDING", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707189");
  private final EnumerationDescriptor.MemberDescriptor VALUE_show_message_action_id_0 = new EnumerationDescriptor.MemberDescriptor("show_message_action_id", "SHOW_MESSAGE", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/9025760234657707190");
  private final EnumerationDescriptor.MemberDescriptor VALUE_comment_out_action_id_0 = new EnumerationDescriptor.MemberDescriptor("comment_out_action_id", "COMMENT", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/5238877291854096301");
  private final EnumerationDescriptor.MemberDescriptor VALUE_click_action_id_0 = new EnumerationDescriptor.MemberDescriptor("click_action_id", "CLICK", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/1943452258409327855");
  private final EnumerationDescriptor.MemberDescriptor VALUE_insert_placeholder_action_id_0 = new EnumerationDescriptor.MemberDescriptor("insert_placeholder_action_id", "INSERT_PLACEHOLDER", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/4058177569375008137");
  private final EnumerationDescriptor.MemberDescriptor VALUE_insert_placeholder_before_action_id_0 = new EnumerationDescriptor.MemberDescriptor("insert_placeholder_before_action_id", "INSERT_PLACEHOLDER_BEFORE", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/474718489010969512");


  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_right_transform_action_id_0, VALUE_delete_action_id_0, VALUE_insert_action_id_0, VALUE_insert_before_action_id_0, VALUE_backspace_action_id_0, VALUE_delete_to_word_end_action_id_0, VALUE_copy_action_id_0, VALUE_cut_action_id_0, VALUE_paste_action_id_0, VALUE_paste_before_action_id_0, VALUE_paste_after_action_id_0, VALUE_left_action_id_0, VALUE_right_action_id_0, VALUE_up_action_id_0, VALUE_down_action_id_0, VALUE_next_action_id_0, VALUE_prev_action_id_0, VALUE_home_action_id_0, VALUE_end_action_id_0, VALUE_page_up_action_id_0, VALUE_page_down_action_id_0, VALUE_root_home_action_id_0, VALUE_root_end_action_id_0, VALUE_local_home_action_id_0, VALUE_local_end_action_id_0, VALUE_select_all_action_id_0, VALUE_select_left_action_id_0, VALUE_select_right_action_id_0, VALUE_select_up_action_id_0, VALUE_select_down_action_id_0, VALUE_select_home_action_id_0, VALUE_select_end_action_id_0, VALUE_select_local_end_action_id_0, VALUE_select_local_home_action_id_0, VALUE_select_next_action_id_0, VALUE_select_previous_action_id_0, VALUE_left_transform_action_id_0, VALUE_complete_action_id_0, VALUE_complete_smart_action_id_0, VALUE_fold_action_id_0, VALUE_unfold_action_id_0, VALUE_fold_all_action_id_0, VALUE_unfold_all_action_id_0, VALUE_toggle_folding_action_id_0, VALUE_show_message_action_id_0, VALUE_comment_out_action_id_0, VALUE_click_action_id_0, VALUE_insert_placeholder_action_id_0, VALUE_insert_placeholder_before_action_id_0);
  }


  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "right_transform_action_id":
        return VALUE_right_transform_action_id_0;
      case "delete_action_id":
        return VALUE_delete_action_id_0;
      case "insert_action_id":
        return VALUE_insert_action_id_0;
      case "insert_before_action_id":
        return VALUE_insert_before_action_id_0;
      case "backspace_action_id":
        return VALUE_backspace_action_id_0;
      case "delete_to_word_end_action_id":
        return VALUE_delete_to_word_end_action_id_0;
      case "copy_action_id":
        return VALUE_copy_action_id_0;
      case "cut_action_id":
        return VALUE_cut_action_id_0;
      case "paste_action_id":
        return VALUE_paste_action_id_0;
      case "paste_before_action_id":
        return VALUE_paste_before_action_id_0;
      case "paste_after_action_id":
        return VALUE_paste_after_action_id_0;
      case "left_action_id":
        return VALUE_left_action_id_0;
      case "right_action_id":
        return VALUE_right_action_id_0;
      case "up_action_id":
        return VALUE_up_action_id_0;
      case "down_action_id":
        return VALUE_down_action_id_0;
      case "next_action_id":
        return VALUE_next_action_id_0;
      case "prev_action_id":
        return VALUE_prev_action_id_0;
      case "home_action_id":
        return VALUE_home_action_id_0;
      case "end_action_id":
        return VALUE_end_action_id_0;
      case "page_up_action_id":
        return VALUE_page_up_action_id_0;
      case "page_down_action_id":
        return VALUE_page_down_action_id_0;
      case "root_home_action_id":
        return VALUE_root_home_action_id_0;
      case "root_end_action_id":
        return VALUE_root_end_action_id_0;
      case "local_home_action_id":
        return VALUE_local_home_action_id_0;
      case "local_end_action_id":
        return VALUE_local_end_action_id_0;
      case "select_all_action_id":
        return VALUE_select_all_action_id_0;
      case "select_left_action_id":
        return VALUE_select_left_action_id_0;
      case "select_right_action_id":
        return VALUE_select_right_action_id_0;
      case "select_up_action_id":
        return VALUE_select_up_action_id_0;
      case "select_down_action_id":
        return VALUE_select_down_action_id_0;
      case "select_home_action_id":
        return VALUE_select_home_action_id_0;
      case "select_end_action_id":
        return VALUE_select_end_action_id_0;
      case "select_local_end_action_id":
        return VALUE_select_local_end_action_id_0;
      case "select_local_home_action_id":
        return VALUE_select_local_home_action_id_0;
      case "select_next_action_id":
        return VALUE_select_next_action_id_0;
      case "select_previous_action_id":
        return VALUE_select_previous_action_id_0;
      case "left_transform_action_id":
        return VALUE_left_transform_action_id_0;
      case "complete_action_id":
        return VALUE_complete_action_id_0;
      case "complete_smart_action_id":
        return VALUE_complete_smart_action_id_0;
      case "fold_action_id":
        return VALUE_fold_action_id_0;
      case "unfold_action_id":
        return VALUE_unfold_action_id_0;
      case "fold_all_action_id":
        return VALUE_fold_all_action_id_0;
      case "unfold_all_action_id":
        return VALUE_unfold_all_action_id_0;
      case "toggle_folding_action_id":
        return VALUE_toggle_folding_action_id_0;
      case "show_message_action_id":
        return VALUE_show_message_action_id_0;
      case "comment_out_action_id":
        return VALUE_comment_out_action_id_0;
      case "click_action_id":
        return VALUE_click_action_id_0;
      case "insert_placeholder_action_id":
        return VALUE_insert_placeholder_action_id_0;
      case "insert_placeholder_before_action_id":
        return VALUE_insert_placeholder_before_action_id_0;
    }
    return null;
  }
}
