package jetbrains.mps.lang.editor.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_DefaultBaseLineEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_DefaultBaseLineEnum() {
    super(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x69c06896a0e4b8a9L, "DefaultBaseLineEnum", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/7620205565664606377");
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_FIRST_0 = new EnumerationDescriptor.MemberDescriptor("FIRST", "first cell baseline", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/7620205565664606378");
  private final EnumerationDescriptor.MemberDescriptor VALUE_CENTER_0 = new EnumerationDescriptor.MemberDescriptor("CENTER", "collection center", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/7620205565664606380");
  private final EnumerationDescriptor.MemberDescriptor VALUE_LAST_0 = new EnumerationDescriptor.MemberDescriptor("LAST", "last cell baseline", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/7620205565664606448");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_FIRST_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_FIRST_0, VALUE_CENTER_0, VALUE_LAST_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "FIRST":
        return VALUE_FIRST_0;
      case "CENTER":
        return VALUE_CENTER_0;
      case "LAST":
        return VALUE_LAST_0;
    }
    return null;
  }
}
