package jetbrains.mps.lang.editor.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_UnderlineStyle extends EnumerationDescriptorBase {

  public EnumerationDescriptor_UnderlineStyle() {
    super(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x1074bc650e6L, "UnderlineStyle", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/1130847686886", PrimitiveTypeId.INTEGER);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_0_0 = new EnumerationDescriptor.MemberDescriptor("0", "as_is", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/1130847686918", "as_is");
  private final EnumerationDescriptor.MemberDescriptor VALUE_1_0 = new EnumerationDescriptor.MemberDescriptor("1", "not_underlined", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/1130847816499", "not_underlined");
  private final EnumerationDescriptor.MemberDescriptor VALUE_2_0 = new EnumerationDescriptor.MemberDescriptor("2", "underlined", "r:00000000-0000-4000-0000-011c8959029e(jetbrains.mps.lang.editor.structure)/1130847833453", "underlined");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_0_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_0_0, VALUE_1_0, VALUE_2_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "0":
        return VALUE_0_0;
      case "1":
        return VALUE_1_0;
      case "2":
        return VALUE_2_0;
    }
    return null;
  }
}
