package testSubtypingTest.model;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.ClassRule;
import jetbrains.mps.lang.test.runtime.TestParametersCache;
import org.junit.Rule;
import jetbrains.mps.lang.test.runtime.RunWithCommand;
import org.junit.Test;
import jetbrains.mps.lang.test.runtime.BaseTestBody;
import jetbrains.mps.lang.test.runtime.TransformationTest;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.test.behavior.INodesTestMethod__BehaviorDescriptor;

@MPSLaunch
public class NullProperties_Test extends BaseTransformationTest {
  @ClassRule
  public static final TestParametersCache ourParamCache = new TestParametersCache(NullProperties_Test.class, "${mps_home}", "r:f6873416-2681-4a14-803b-33f9e8bdd0a6(testSubtypingTest.model)", false);
  @Rule
  public final RunWithCommand myWithCommandRule = new RunWithCommand(this);

  public NullProperties_Test() {
    super(ourParamCache);
  }

  @Test
  public void test_NodeErrorCheck8681827087508331151() throws Throwable {
    new NullProperties_Test.TestBody(this).test_NodeErrorCheck8681827087508331151();
  }
  @Test
  public void test_NodeErrorCheck8681827087508331336() throws Throwable {
    new NullProperties_Test.TestBody(this).test_NodeErrorCheck8681827087508331336();
  }
  @Test
  public void test_ErrorMessagesCheck706089536802542545() throws Throwable {
    new NullProperties_Test.TestBody(this).test_ErrorMessagesCheck706089536802542545();
  }
  @Test
  public void test_NodeErrorCheck3029960565848077192() throws Throwable {
    new NullProperties_Test.TestBody(this).test_NodeErrorCheck3029960565848077192();
  }
  @Test
  public void test_NodeErrorCheck3029960565848077546() throws Throwable {
    new NullProperties_Test.TestBody(this).test_NodeErrorCheck3029960565848077546();
  }
  @Test
  public void test_ErrorMessagesCheck706089536802542565() throws Throwable {
    new NullProperties_Test.TestBody(this).test_ErrorMessagesCheck706089536802542565();
  }
  @Test
  public void test_ErrorMessagesCheck706089536802542585() throws Throwable {
    new NullProperties_Test.TestBody(this).test_ErrorMessagesCheck706089536802542585();
  }

  /*package*/ static class TestBody extends BaseTestBody {

    /*package*/ TestBody(TransformationTest owner) {
      super(owner);
    }


    public void test_NodeErrorCheck8681827087508331151() throws Exception {
      SNode operation = SNodeOperations.cast(getRealNodeById("8681827087508331151"), MetaAdapterFactory.getInterfaceConcept(0x8585453e6bfb4d80L, 0x98deb16074f1d86cL, 0x1510445f8a2c272dL, "jetbrains.mps.lang.test.structure.INodesTestMethod"));
      INodesTestMethod__BehaviorDescriptor.perform_id1kgh5YabdhC.invoke(operation, getRealNodeById("706089536802542537"));
    }
    public void test_NodeErrorCheck8681827087508331336() throws Exception {
      SNode operation = SNodeOperations.cast(getRealNodeById("8681827087508331336"), MetaAdapterFactory.getInterfaceConcept(0x8585453e6bfb4d80L, 0x98deb16074f1d86cL, 0x1510445f8a2c272dL, "jetbrains.mps.lang.test.structure.INodesTestMethod"));
      INodesTestMethod__BehaviorDescriptor.perform_id1kgh5YabdhC.invoke(operation, getRealNodeById("706089536802542541"));
    }
    public void test_ErrorMessagesCheck706089536802542545() throws Exception {
      SNode operation = SNodeOperations.cast(getRealNodeById("706089536802542545"), MetaAdapterFactory.getInterfaceConcept(0x8585453e6bfb4d80L, 0x98deb16074f1d86cL, 0x1510445f8a2c272dL, "jetbrains.mps.lang.test.structure.INodesTestMethod"));
      INodesTestMethod__BehaviorDescriptor.perform_id1kgh5YabdhC.invoke(operation, getRealNodeById("706089536802542527"));
    }
    public void test_NodeErrorCheck3029960565848077192() throws Exception {
      SNode operation = SNodeOperations.cast(getRealNodeById("3029960565848077192"), MetaAdapterFactory.getInterfaceConcept(0x8585453e6bfb4d80L, 0x98deb16074f1d86cL, 0x1510445f8a2c272dL, "jetbrains.mps.lang.test.structure.INodesTestMethod"));
      INodesTestMethod__BehaviorDescriptor.perform_id1kgh5YabdhC.invoke(operation, getRealNodeById("706089536802542557"));
    }
    public void test_NodeErrorCheck3029960565848077546() throws Exception {
      SNode operation = SNodeOperations.cast(getRealNodeById("3029960565848077546"), MetaAdapterFactory.getInterfaceConcept(0x8585453e6bfb4d80L, 0x98deb16074f1d86cL, 0x1510445f8a2c272dL, "jetbrains.mps.lang.test.structure.INodesTestMethod"));
      INodesTestMethod__BehaviorDescriptor.perform_id1kgh5YabdhC.invoke(operation, getRealNodeById("706089536802542561"));
    }
    public void test_ErrorMessagesCheck706089536802542565() throws Exception {
      SNode operation = SNodeOperations.cast(getRealNodeById("706089536802542565"), MetaAdapterFactory.getInterfaceConcept(0x8585453e6bfb4d80L, 0x98deb16074f1d86cL, 0x1510445f8a2c272dL, "jetbrains.mps.lang.test.structure.INodesTestMethod"));
      INodesTestMethod__BehaviorDescriptor.perform_id1kgh5YabdhC.invoke(operation, getRealNodeById("706089536802542547"));
    }
    public void test_ErrorMessagesCheck706089536802542585() throws Exception {
      SNode operation = SNodeOperations.cast(getRealNodeById("706089536802542585"), MetaAdapterFactory.getInterfaceConcept(0x8585453e6bfb4d80L, 0x98deb16074f1d86cL, 0x1510445f8a2c272dL, "jetbrains.mps.lang.test.structure.INodesTestMethod"));
      INodesTestMethod__BehaviorDescriptor.perform_id1kgh5YabdhC.invoke(operation, getRealNodeById("706089536802542567"));
    }

  }
}
