package jetbrains.mps.lang.script.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_ScriptType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ScriptType() {
    super(0xeddeefac2d64437L, 0xbc2cde50fd4ce470L, 0x498b4f71ee081150L, "ScriptType", "r:00000000-0000-4000-0000-011c89590323(jetbrains.mps.lang.script.structure)/5299416737274925392");
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_enhancement_0 = new EnumerationDescriptor.MemberDescriptor("enhancement", "enhancement", "r:00000000-0000-4000-0000-011c89590323(jetbrains.mps.lang.script.structure)/5299416737274925393");
  private final EnumerationDescriptor.MemberDescriptor VALUE_migration_0 = new EnumerationDescriptor.MemberDescriptor("migration", "migration", "r:00000000-0000-4000-0000-011c89590323(jetbrains.mps.lang.script.structure)/5299416737274925394");


  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_enhancement_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_enhancement_0, VALUE_migration_0);
  }


  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "enhancement":
        return VALUE_enhancement_0;
      case "migration":
        return VALUE_migration_0;
    }
    return null;
  }
}
