package jetbrains.mps.baseLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;

public class IconContainer {
  protected static IconResource RESOURCE_a0a3a0a9b0dl = new IconResource("annotationtype.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a4a0a41b0dl = new IconResource("anonymousClass.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a1a0a03b0dl = new IconResource("method.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a01a0a05b0dl = new IconResource("class.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a1a0a56b0dl = new IconResource("parameter.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a3a0a38b0dl = new IconResource("enum.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a2a0a29b0dl = new IconResource("field.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a2a0a051b0dl = new IconResource("classInitializer.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a2a0a251b0dl = new IconResource("method.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a3a0a751b0dl = new IconResource("interfaceType.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a3a0a371b0dl = new IconResource("variable.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a3a0a791b0dl = new IconResource("parameter.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a3a0a132b0dl = new IconResource("field.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a2a0a332b0dl = new IconResource("classInitializer.png", IconContainer.class);
}
