package jetbrains.mps.lang.generator.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_GeneratorMessageType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_GeneratorMessageType() {
    super(0xb401a68083254110L, 0x8fd384331ff25befL, 0x11055c71875L, "GeneratorMessageType", "r:00000000-0000-4000-0000-011c895902e8(jetbrains.mps.lang.generator.structure)/1169670215797");
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_info_0 = new EnumerationDescriptor.MemberDescriptor("info", "info", "r:00000000-0000-4000-0000-011c895902e8(jetbrains.mps.lang.generator.structure)/1169670215798");
  private final EnumerationDescriptor.MemberDescriptor VALUE_warning_0 = new EnumerationDescriptor.MemberDescriptor("warning", "warning", "r:00000000-0000-4000-0000-011c895902e8(jetbrains.mps.lang.generator.structure)/1169670280596");
  private final EnumerationDescriptor.MemberDescriptor VALUE_error_0 = new EnumerationDescriptor.MemberDescriptor("error", "error", "r:00000000-0000-4000-0000-011c895902e8(jetbrains.mps.lang.generator.structure)/1169670287832");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_info_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_info_0, VALUE_warning_0, VALUE_error_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "info":
        return VALUE_info_0;
      case "warning":
        return VALUE_warning_0;
      case "error":
        return VALUE_error_0;
    }
    return null;
  }
}
