package jetbrains.mps.core.tool.environment.classloading;

/*Generated by MPS */

import java.io.File;
import jetbrains.mps.core.tool.environment.common.StringUtil;

/**
 * 
 * @deprecated Leftover of some old IDEA code copied to MPS to get it started from Ant, cease using, replace with IDEA or MPS counterparts.
 */
@Deprecated
public class ClassloaderUtil {
  @Deprecated
  private ClassloaderUtil() {
  }

  @SuppressWarnings(value = {"HardCodedStringLiteral"})
  public static boolean isJarOrZip(File file) {
    if (file.isDirectory()) {
      return false;
    }
    final String name = file.getName();
    return StringUtil.endsWithIgnoreCase(name, ".jar") || StringUtil.endsWithIgnoreCase(name, ".zip");
  }
}
