package typesystemIntegration.languageChecker;

/*Generated by MPS */

import jetbrains.mps.checkers.RefScopeChecker;
import jetbrains.mps.errors.item.EditorQuickFix;
import org.jetbrains.mps.openapi.model.SReference;
import org.jetbrains.mps.openapi.module.SRepository;
import jetbrains.mps.typesystem.checking.EditorContextQuickfix;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.resolve.ResolverComponent;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.resolve.ReferenceResolverUtils;

public class RefScopeCheckerInEditor extends RefScopeChecker {
  @Override
  protected EditorQuickFix createResolveReferenceQuickfix(SReference reference, SRepository repository, boolean executeImmediately) {
    return new RefScopeCheckerInEditor.ResolveReferenceEditorBasedQuickFix(reference, repository, executeImmediately);
  }

  private static class ResolveReferenceEditorBasedQuickFix extends RefScopeChecker.ResolveReferenceQuickFix implements EditorContextQuickfix {
    public ResolveReferenceEditorBasedQuickFix(SReference reference, SRepository repository, boolean executeImmediately) {
      super(reference, executeImmediately);
    }
    @Override
    public void execute(EditorContext editorContext) {
      if (ResolverComponent.getInstance().resolveScopesOnly(myReference, editorContext.getRepository())) {
        return;
      }
      SNode sourceNode = myReference.getSourceNode();
      if (sourceNode == null) {
        return;
      }
      final String resolveInfo = ReferenceResolverUtils.getResolveInfo(myReference, sourceNode);
      if (resolveInfo == null) {
        return;
      }
      EditorBasedReferenceResolverUtils.resolveInEditor(editorContext.getEditorComponent(), sourceNode, resolveInfo, myReference.getLink().getName());
    }
  }
}
