package jetbrains.mps.checkers;

/*Generated by MPS */

import jetbrains.mps.errors.item.IssueKindReportItem;
import org.jetbrains.mps.openapi.module.SRepository;
import org.jetbrains.mps.openapi.util.Consumer;
import org.jetbrains.mps.openapi.util.ProgressMonitor;
import org.jetbrains.mps.openapi.util.SubProgressKind;

public class CategoryShowingChecker<O, I extends IssueKindReportItem> implements IAbstractChecker<O, I> {
  private IAbstractChecker<O, ? extends I> myOrigin;
  private String myCategory;
  public CategoryShowingChecker(IChecker<O, ? extends I> origin) {
    myOrigin = origin;
    myCategory = origin.getCategory();
  }

  @Override
  public void check(O toCheck, SRepository repository, Consumer<? super I> errorCollector, ProgressMonitor monitor) {
    monitor.start(myCategory, 1);
    myOrigin.check(toCheck, repository, errorCollector, monitor.subTask(1, SubProgressKind.IGNORED));
    monitor.done();
  }
}
