package jetbrains.mps.lang.test.runtime;

/*Generated by MPS */

import org.junit.AssumptionViolatedException;
import org.jetbrains.annotations.NotNull;

/*package*/ final class EnvironmentIsNullException extends AssumptionViolatedException {
  public EnvironmentIsNullException(@NotNull String testName, @NotNull String projectPath) {
    super(String.format("The test '%s' needs an Environment instance to access the project at '%s'", testName, projectPath));
  }
}
