package jetbrains.mps.lang.test.runtime;

/*Generated by MPS */

import org.junit.AssumptionViolatedException;
import org.jetbrains.annotations.NotNull;

/*package*/ final class ExpandedProjectPathIsNullException extends AssumptionViolatedException {
  public ExpandedProjectPathIsNullException(@NotNull String projectPath) {
    super(String.format("The macros in the project path '%s' is reduced to null", projectPath));
  }
}
