package jetbrains.mps.lang.test.runtime;

/*Generated by MPS */

import org.junit.AssumptionViolatedException;

/*package*/ final class ProjectPathIsNullException extends AssumptionViolatedException {
  public ProjectPathIsNullException() {
    super("The project path was not specified in the TestInfo root.");
  }
}
