package jetbrains.mps.lang.findUsages.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.cells.EditorCell;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.editor.runtime.cells.AbstractCellAction;
import jetbrains.mps.editor.runtime.deletionApprover.DeletionApproverUtil;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class ForConstantCellsInTheExpression {
  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setAction(CellActionType.DELETE, new ForConstantCellsInTheExpression.ForConstantCellsInTheExpression_DELETE(node));
    editorCell.setAction(CellActionType.BACKSPACE, new ForConstantCellsInTheExpression.ForConstantCellsInTheExpression_BACKSPACE(node));
  }
  public static class ForConstantCellsInTheExpression_DELETE extends AbstractCellAction {
    /*package*/ SNode myNode;
    public ForConstantCellsInTheExpression_DELETE(SNode node) {
      this.myNode = node;
    }
    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }
    public void execute_internal(EditorContext editorContext, SNode node) {
      if (DeletionApproverUtil.approve(editorContext, node)) {
        return;
      }
      SNodeOperations.deleteNode(node);
    }
  }
  public static class ForConstantCellsInTheExpression_BACKSPACE extends AbstractCellAction {
    /*package*/ SNode myNode;
    public ForConstantCellsInTheExpression_BACKSPACE(SNode node) {
      this.myNode = node;
    }
    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }
    public void execute_internal(EditorContext editorContext, SNode node) {
      if (DeletionApproverUtil.approve(editorContext, node)) {
        return;
      }
      SNodeOperations.deleteNode(node);
    }
  }
}
