package jetbrains.mps.ide.findusages.findalgorithm.finders;

/*Generated by MPS */


import jetbrains.mps.ide.findusages.model.SearchQuery;
import jetbrains.mps.ide.findusages.model.SearchResult;
import jetbrains.mps.ide.findusages.model.SearchResults;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.util.ProgressMonitor;

public abstract class BaseFinder implements Finder {
  @NotNull
  @Override
  public SearchResults<?> find(@NotNull SearchQuery query, ProgressMonitor monitor) {
    SearchResults results = new SearchResults();
    find(query, new FindCallback() {
      @Override
      public void onUsageFound(@NotNull SearchResult<?> result) {
        results.add(result);
      }

      @Override
      public void onSearchedObjectsCalculated(@NotNull SearchedObjects<?> searchedObjects) {
        results.getSearchedNodes().addAll(searchedObjects.getElements());
      }
    }, monitor);
    return results;
  }

  @Override
  public String getDescription() {
    // to remove after 3.4, it's simpler to refactor with this body 
    return getClass().getSimpleName();
  }
}
