package jetbrains.mps.lang.plugin.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_ToolPosition extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ToolPosition() {
    super(0x28f9e4973b424291L, 0xaeba0a1039153ab1L, 0x22ace24ea9f74877L, "ToolPosition", "r:00000000-0000-4000-0000-011c89590368(jetbrains.mps.lang.plugin.structure)/2498620720770664567", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_BOTTOM_0 = new EnumerationDescriptor.MemberDescriptor("BOTTOM", "bottom", "r:00000000-0000-4000-0000-011c89590368(jetbrains.mps.lang.plugin.structure)/2498620720770664568", "bottom");
  private final EnumerationDescriptor.MemberDescriptor VALUE_TOP_0 = new EnumerationDescriptor.MemberDescriptor("TOP", "top", "r:00000000-0000-4000-0000-011c89590368(jetbrains.mps.lang.plugin.structure)/2498620720770664569", "top");
  private final EnumerationDescriptor.MemberDescriptor VALUE_LEFT_0 = new EnumerationDescriptor.MemberDescriptor("LEFT", "left", "r:00000000-0000-4000-0000-011c89590368(jetbrains.mps.lang.plugin.structure)/2498620720770664570", "left");
  private final EnumerationDescriptor.MemberDescriptor VALUE_RIGHT_0 = new EnumerationDescriptor.MemberDescriptor("RIGHT", "right", "r:00000000-0000-4000-0000-011c89590368(jetbrains.mps.lang.plugin.structure)/2498620720770664571", "right");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_BOTTOM_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_BOTTOM_0, VALUE_TOP_0, VALUE_LEFT_0, VALUE_RIGHT_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "BOTTOM":
        return VALUE_BOTTOM_0;
      case "TOP":
        return VALUE_TOP_0;
      case "LEFT":
        return VALUE_LEFT_0;
      case "RIGHT":
        return VALUE_RIGHT_0;
    }
    return null;
  }
}
