package jetbrains.mps.transformation.test.inputLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_Option extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Option() {
    super(0xab0ae915e3b54f35L, 0xb55ac655d649a03cL, 0x11645a380abL, "Option", "r:00000000-0000-4000-0000-011c895905f4(jetbrains.mps.transformation.test.inputLang.structure)/1195169251499");
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_option_default_0 = new EnumerationDescriptor.MemberDescriptor("option_default", "option_default", "r:00000000-0000-4000-0000-011c895905f4(jetbrains.mps.transformation.test.inputLang.structure)/1195169251500");
  private final EnumerationDescriptor.MemberDescriptor VALUE_option_1_0 = new EnumerationDescriptor.MemberDescriptor("option_1", "option_1", "r:00000000-0000-4000-0000-011c895905f4(jetbrains.mps.transformation.test.inputLang.structure)/1195169295907");
  private final EnumerationDescriptor.MemberDescriptor VALUE_drop_it_0 = new EnumerationDescriptor.MemberDescriptor("drop_it", "drop it", "r:00000000-0000-4000-0000-011c895905f4(jetbrains.mps.transformation.test.inputLang.structure)/1202780730330");


  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_option_default_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_option_default_0, VALUE_option_1_0, VALUE_drop_it_0);
  }


  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "option_default":
        return VALUE_option_default_0;
      case "option_1":
        return VALUE_option_1_0;
      case "drop_it":
        return VALUE_drop_it_0;
    }
    return null;
  }
}
