package jetbrains.mps.transformation.test.inputLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_UseInTest extends EnumerationDescriptorBase {

  public EnumerationDescriptor_UseInTest() {
    super(0xab0ae915e3b54f35L, 0xb55ac655d649a03cL, 0x117eb3f7611L, "UseInTest", "r:00000000-0000-4000-0000-011c895905f4(jetbrains.mps.transformation.test.inputLang.structure)/1202242680337");
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_test1_0 = new EnumerationDescriptor.MemberDescriptor("test1", "test1", "r:00000000-0000-4000-0000-011c895905f4(jetbrains.mps.transformation.test.inputLang.structure)/1202242680338");
  private final EnumerationDescriptor.MemberDescriptor VALUE_getPrevInputTest_0 = new EnumerationDescriptor.MemberDescriptor("getPrevInputTest", "getPrevInputTest", "r:00000000-0000-4000-0000-011c895905f4(jetbrains.mps.transformation.test.inputLang.structure)/1202242753917");
  private final EnumerationDescriptor.MemberDescriptor VALUE_reduceInheritors_0 = new EnumerationDescriptor.MemberDescriptor("reduceInheritors", "reduceInheritors", "r:00000000-0000-4000-0000-011c895905f4(jetbrains.mps.transformation.test.inputLang.structure)/1206459825805");
  private final EnumerationDescriptor.MemberDescriptor VALUE_reduceExpressionToStatement_0 = new EnumerationDescriptor.MemberDescriptor("reduceExpressionToStatement", "reduceExpressionToStatement", "r:00000000-0000-4000-0000-011c895905f4(jetbrains.mps.transformation.test.inputLang.structure)/1209146734796");
  private final EnumerationDescriptor.MemberDescriptor VALUE_dontApplyReductionTwice_0 = new EnumerationDescriptor.MemberDescriptor("dontApplyReductionTwice", "dontApplyReductionTwice", "r:00000000-0000-4000-0000-011c895905f4(jetbrains.mps.transformation.test.inputLang.structure)/1209603553188");
  private final EnumerationDescriptor.MemberDescriptor VALUE_weaveManyToSingularChild_0 = new EnumerationDescriptor.MemberDescriptor("weaveManyToSingularChild", "weaveManyToSingularChild", "r:00000000-0000-4000-0000-011c895905f4(jetbrains.mps.transformation.test.inputLang.structure)/1218736527492");
  private final EnumerationDescriptor.MemberDescriptor VALUE_reduceOneToMany_0 = new EnumerationDescriptor.MemberDescriptor("reduceOneToMany", "reduceOneToMany", "r:00000000-0000-4000-0000-011c895905f4(jetbrains.mps.transformation.test.inputLang.structure)/341670684286865622");
  private final EnumerationDescriptor.MemberDescriptor VALUE_argsInTemplDeclRef_0 = new EnumerationDescriptor.MemberDescriptor("argsInTemplDeclRef", "argsInTemplDeclRef", "r:00000000-0000-4000-0000-011c895905f4(jetbrains.mps.transformation.test.inputLang.structure)/7496726876599722366");
  private final EnumerationDescriptor.MemberDescriptor VALUE_argsInTemplateCall_0 = new EnumerationDescriptor.MemberDescriptor("argsInTemplateCall", "Expressions in ITemplateCall arguments", "r:00000000-0000-4000-0000-011c895905f4(jetbrains.mps.transformation.test.inputLang.structure)/207553032706660027");
  private final EnumerationDescriptor.MemberDescriptor VALUE_none_0 = new EnumerationDescriptor.MemberDescriptor("none", "none", "r:00000000-0000-4000-0000-011c895905f4(jetbrains.mps.transformation.test.inputLang.structure)/1202242822699");


  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_none_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_test1_0, VALUE_getPrevInputTest_0, VALUE_reduceInheritors_0, VALUE_reduceExpressionToStatement_0, VALUE_dontApplyReductionTwice_0, VALUE_weaveManyToSingularChild_0, VALUE_reduceOneToMany_0, VALUE_argsInTemplDeclRef_0, VALUE_argsInTemplateCall_0, VALUE_none_0);
  }


  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "test1":
        return VALUE_test1_0;
      case "getPrevInputTest":
        return VALUE_getPrevInputTest_0;
      case "reduceInheritors":
        return VALUE_reduceInheritors_0;
      case "reduceExpressionToStatement":
        return VALUE_reduceExpressionToStatement_0;
      case "dontApplyReductionTwice":
        return VALUE_dontApplyReductionTwice_0;
      case "weaveManyToSingularChild":
        return VALUE_weaveManyToSingularChild_0;
      case "reduceOneToMany":
        return VALUE_reduceOneToMany_0;
      case "argsInTemplDeclRef":
        return VALUE_argsInTemplDeclRef_0;
      case "argsInTemplateCall":
        return VALUE_argsInTemplateCall_0;
      case "none":
        return VALUE_none_0;
    }
    return null;
  }
}
