package jetbrains.mps.lang.structure.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_EnumerationMemberIdentifierPolicy extends EnumerationDescriptorBase {

  public EnumerationDescriptor_EnumerationMemberIdentifierPolicy() {
    super(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0x116d5fab105L, "EnumerationMemberIdentifierPolicy", "r:00000000-0000-4000-0000-011c89590292(jetbrains.mps.lang.structure.structure)/1197590884613", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_derive_from_presentation_0 = new EnumerationDescriptor.MemberDescriptor("derive_from_presentation", "derive from presentation", "r:00000000-0000-4000-0000-011c89590292(jetbrains.mps.lang.structure.structure)/1197590884614", "derive_from_presentation");
  private final EnumerationDescriptor.MemberDescriptor VALUE_derive_from_internal_value_0 = new EnumerationDescriptor.MemberDescriptor("derive_from_internal_value", "derive from internal value", "r:00000000-0000-4000-0000-011c89590292(jetbrains.mps.lang.structure.structure)/1197591048630", "derive_from_internal_value");
  private final EnumerationDescriptor.MemberDescriptor VALUE_custom_0 = new EnumerationDescriptor.MemberDescriptor("custom", "custom", "r:00000000-0000-4000-0000-011c89590292(jetbrains.mps.lang.structure.structure)/1197591075491", "custom");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_derive_from_presentation_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_derive_from_presentation_0, VALUE_derive_from_internal_value_0, VALUE_custom_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "derive_from_presentation":
        return VALUE_derive_from_presentation_0;
      case "derive_from_internal_value":
        return VALUE_derive_from_internal_value_0;
      case "custom":
        return VALUE_custom_0;
    }
    return null;
  }
}
