package jetbrains.mps.lang.structure.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_LinkMetaclass extends EnumerationDescriptorBase {

  public EnumerationDescriptor_LinkMetaclass() {
    super(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0xfc6f4e95b7L, "LinkMetaclass", "r:00000000-0000-4000-0000-011c89590292(jetbrains.mps.lang.structure.structure)/1084199179703");
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_reference_0 = new EnumerationDescriptor.MemberDescriptor("reference", "reference", "r:00000000-0000-4000-0000-011c89590292(jetbrains.mps.lang.structure.structure)/1084199179704");
  private final EnumerationDescriptor.MemberDescriptor VALUE_aggregation_0 = new EnumerationDescriptor.MemberDescriptor("aggregation", "aggregation", "r:00000000-0000-4000-0000-011c89590292(jetbrains.mps.lang.structure.structure)/1084199179705");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_reference_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_reference_0, VALUE_aggregation_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "reference":
        return VALUE_reference_0;
      case "aggregation":
        return VALUE_aggregation_0;
    }
    return null;
  }
}
