package jetbrains.mps.lang.editor.editorTest.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_MenuTraceEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_MenuTraceEnum() {
    super(0x81f0abb8d71e4d13L, 0xa0c1d2291fbb28b7L, 0x326616b1fdb131b2L, "MenuTraceEnum", "r:1a7fc406-f263-498c-a126-51036fe6a9da(jetbrains.mps.lang.editor.editorTest.structure)/3631615103242154418");
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_enum1_0 = new EnumerationDescriptor.MemberDescriptor("enum1", "enum1", "r:1a7fc406-f263-498c-a126-51036fe6a9da(jetbrains.mps.lang.editor.editorTest.structure)/3631615103242154419");
  private final EnumerationDescriptor.MemberDescriptor VALUE_enum2_0 = new EnumerationDescriptor.MemberDescriptor("enum2", "enum2", "r:1a7fc406-f263-498c-a126-51036fe6a9da(jetbrains.mps.lang.editor.editorTest.structure)/3631615103242154420");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_enum1_0, VALUE_enum2_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "enum1":
        return VALUE_enum1_0;
      case "enum2":
        return VALUE_enum2_0;
    }
    return null;
  }
}
