package jetbrains.mps.tool.common;

/*Generated by MPS */

import jetbrains.mps.util.annotation.ToRemove;
import org.jetbrains.annotations.NotNull;

/**
 * 
 * 
 * @deprecated in MPS, there are no more uses of this interface nor uses of subclasses. Unless anybody needs this one, shall cease to exist.
 */
@Deprecated
@ToRemove(version = 2018.3)
public interface IMessageFormat {
  StringBuffer escapeBuildMessage(@NotNull StringBuffer message);
  String escapeBuildMessage(@NotNull String message);
  String getLinesSeparator();
  String formatTestStart(@NotNull String testName);
  String formatTestFinish(@NotNull String testName);
  CharSequence formatTestFailure(@NotNull String testName, @NotNull String message, @NotNull CharSequence details);
  boolean isBuildServerMessage(@NotNull CharSequence message);
  int hasContinuation(@NotNull String message);
}
