package jetbrains.mps.samples.agreementLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_Unit extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Unit() {
    super(0x144f7012c2d543beL, 0xbe2b4bfb7dff6503L, 0x102dc0a8282L, "Unit", "r:00000000-0000-4000-0000-011c8959040a(jetbrains.mps.samples.agreementLanguage.structure)/1111793238658");
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_USD_KWH_0 = new EnumerationDescriptor.MemberDescriptor("USD_KWH", "USD_KWH", "r:00000000-0000-4000-0000-011c8959040a(jetbrains.mps.samples.agreementLanguage.structure)/1111793245330");
  private final EnumerationDescriptor.MemberDescriptor VALUE_USD_0 = new EnumerationDescriptor.MemberDescriptor("USD", "USD", "r:00000000-0000-4000-0000-011c8959040a(jetbrains.mps.samples.agreementLanguage.structure)/1111793298691");
  private final EnumerationDescriptor.MemberDescriptor VALUE_KWH_0 = new EnumerationDescriptor.MemberDescriptor("KWH", "KWH", "r:00000000-0000-4000-0000-011c8959040a(jetbrains.mps.samples.agreementLanguage.structure)/1111793319239");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_USD_KWH_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_USD_KWH_0, VALUE_USD_0, VALUE_KWH_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "USD_KWH":
        return VALUE_USD_KWH_0;
      case "USD":
        return VALUE_USD_0;
      case "KWH":
        return VALUE_KWH_0;
    }
    return null;
  }
}
