package jetbrains.mps.tool.environment;

/*Generated by MPS */


public abstract class EnvironmentSetupException extends RuntimeException {
  public EnvironmentSetupException(String message, Throwable cause) {
    super(message, cause);
  }

  public EnvironmentSetupException(String message) {
    super(message);
  }
}
