package jetbrains.mps.lang.test.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_Level extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Level() {
    super(0x8585453e6bfb4d80L, 0x98deb16074f1d86cL, 0x486f8079df3673c3L, "Level", "r:00000000-0000-4000-0000-011c89590388(jetbrains.mps.lang.test.structure)/5219531754069980099");
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_OFF_0 = new EnumerationDescriptor.MemberDescriptor("OFF", "OFF", "r:00000000-0000-4000-0000-011c89590388(jetbrains.mps.lang.test.structure)/5219531754069980100");
  private final EnumerationDescriptor.MemberDescriptor VALUE_FATAL_0 = new EnumerationDescriptor.MemberDescriptor("FATAL", "FATAL", "r:00000000-0000-4000-0000-011c89590388(jetbrains.mps.lang.test.structure)/5219531754069980101");
  private final EnumerationDescriptor.MemberDescriptor VALUE_ERROR_0 = new EnumerationDescriptor.MemberDescriptor("ERROR", "ERROR", "r:00000000-0000-4000-0000-011c89590388(jetbrains.mps.lang.test.structure)/5219531754069980106");
  private final EnumerationDescriptor.MemberDescriptor VALUE_WARN_0 = new EnumerationDescriptor.MemberDescriptor("WARN", "WARN", "r:00000000-0000-4000-0000-011c89590388(jetbrains.mps.lang.test.structure)/5219531754069980113");
  private final EnumerationDescriptor.MemberDescriptor VALUE_INFO_0 = new EnumerationDescriptor.MemberDescriptor("INFO", "INFO", "r:00000000-0000-4000-0000-011c89590388(jetbrains.mps.lang.test.structure)/5219531754069980122");
  private final EnumerationDescriptor.MemberDescriptor VALUE_DEBUG_0 = new EnumerationDescriptor.MemberDescriptor("DEBUG", "DEBUG", "r:00000000-0000-4000-0000-011c89590388(jetbrains.mps.lang.test.structure)/5219531754069980133");
  private final EnumerationDescriptor.MemberDescriptor VALUE_TRACE_0 = new EnumerationDescriptor.MemberDescriptor("TRACE", "TRACE", "r:00000000-0000-4000-0000-011c89590388(jetbrains.mps.lang.test.structure)/5219531754069980146");
  private final EnumerationDescriptor.MemberDescriptor VALUE_ALL_0 = new EnumerationDescriptor.MemberDescriptor("ALL", "ALL", "r:00000000-0000-4000-0000-011c89590388(jetbrains.mps.lang.test.structure)/5219531754069980161");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_OFF_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_OFF_0, VALUE_FATAL_0, VALUE_ERROR_0, VALUE_WARN_0, VALUE_INFO_0, VALUE_DEBUG_0, VALUE_TRACE_0, VALUE_ALL_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "OFF":
        return VALUE_OFF_0;
      case "FATAL":
        return VALUE_FATAL_0;
      case "ERROR":
        return VALUE_ERROR_0;
      case "WARN":
        return VALUE_WARN_0;
      case "INFO":
        return VALUE_INFO_0;
      case "DEBUG":
        return VALUE_DEBUG_0;
      case "TRACE":
        return VALUE_TRACE_0;
      case "ALL":
        return VALUE_ALL_0;
    }
    return null;
  }
}
