package jetbrains.mps.baseLanguage.jdk8.actions;

/*Generated by MPS */

import jetbrains.mps.actions.descriptor.BaseActionAspectDescriptor;
import jetbrains.mps.openapi.actions.descriptor.ActionAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.actions.descriptor.CopyPreProcessor;
import java.util.Arrays;
import jetbrains.mps.openapi.actions.descriptor.PastePostProcessor;
import jetbrains.mps.openapi.actions.descriptor.PasteWrapper;

public class ActionAspectDescriptorImpl extends BaseActionAspectDescriptor implements ActionAspectDescriptor {

  @Override
  public Collection<NodeFactory> getFactories(SAbstractConcept concept) {
    return Collections.<NodeFactory>emptyList();
  }

  @Override
  public Collection<CopyPreProcessor> getCopyPreProcessors() {
    return Arrays.asList(new CopyPreProcessor[]{new copyPasteExtendingWithDefaultModifier_CopyPreProcessor_0()});
  }
  @Override
  public Collection<PastePostProcessor> getPastePostProcessors() {
    return Arrays.asList(new PastePostProcessor[]{new copyPasteExtendingWithDefaultModifier_PastePostProcessor_0()});
  }
  @Override
  public Collection<PasteWrapper> getPasteWrappers() {
    return Arrays.asList(new PasteWrapper[]{new PasteOverridingForDefaultMethodsAsWell_PasteWrapper_0()});
  }
}
